# when param is used to differentiate the tasks for Debian-based OS (e.g. Ubuntu) and non-Debian OS (e.g. macOS, CentOS)
---
- hosts: all
  tasks:
    - name: Debian-based OS
      debug:
        msg: "Install npm directly via package manager"
      when: ansible_os_family == "Debian"

    - name: Install npm
      apt:
       name: npm
       state: latest
      when: ansible_os_family == "Debian"
    
    - name: Check version of npm
      command: npm -v
      when: ansible_os_family == "Debian"

    - name: Install packages based on package.json using the npm
      command: npm install
      when: ansible_os_family == "Debian"

    - name: Non Debian-based OS
      debug:
        msg: "Install npm via nvm"
      when: ansible_os_family != "Debian"

    - name: Get nvm.sh
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh
        dest: "{{ playbook_dir }}"
        mode: '0755'
      when: ansible_os_family != "Debian"

    - name: Create $PWD/.nvm directory
      file: path="{{ playbook_dir }}/.nvm" state="directory"
      when: ansible_os_family != "Debian"

    - name: Install nvm
      shell: >
        export NVM_DIR="{{ playbook_dir }}/.nvm";
        {{ playbook_dir }}/install.sh;
      when: ansible_os_family != "Debian"

    - name: "Install and Use Node.js {{ node_js_version }}"
      shell: >
        export NVM_DIR="{{ playbook_dir }}/.nvm";
        source $NVM_DIR/nvm.sh;
        nvm install v13.5.0;
        nvm use --delete-prefix v13.5.0/dev/null --silent;
        which npm;
      register: npm_output
      when: ansible_os_family != "Debian"

    - name: Save location of npm
      set_fact: npm_location={{ npm_output.stdout_lines | last }}
      when: ansible_os_family != "Debian"

    - name: Set npm location into path of ansible environment 
      debug:
        msg: "{{ npm_location }}:{{ ansible_env.PATH }}"
      when: ansible_os_family != "Debian"

    - name: Save location of npm
      set_fact: bin_location={{ npm_location | dirname }}
      when: ansible_os_family != "Debian"

    - name: Install packages based on package.json using the npm installed with nvm v0.35.2.
      environment:
        PATH: "{{ bin_location }}:{{ ansible_env.PATH }}"
      npm:
        path: "{{ playbook_dir | dirname }}"
      when: ansible_os_family != "Debian"



